version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "local--save-picture"
s3_bucket = "local-test-bucket-whatsapp"
s3_prefix = "local"
region = "ap-southeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
